cmd/harpoon/main.go

It used to look for files to run the engine method on
in the repository tree with the path containing the
subdirectory string.
Now it gets the subdirectory tree and runs the engine method
on all files in the tree with a json file extenstion.
Fixes: https://github.com/redhat-et/harpoon/issues/43

Fix way harpoon looks for subdirectory specified in config

---

examples/kube/example.yaml

This changes the pod name to not coincide with the container name
in the kube example.yaml

Fix kube example

---

.github/workflows/docker-image.yml
examples/kube/example.yaml

This action tests the kube method is not broken by expecting a single
pod named colors_pod to be created as a result of running harpoon on
the kube example.
Depends on: #59 

Create github action for kube method

---

pkg/engine/harpoon.go

This commit quickly fixes an issue where added files were not being 
recognized this is due to the way we are generating the diff in findDiff.
This is a quick solution, the problem lies in findDiff so that should be
changed to avoid confusion.
Fixes #94

fix change to look at added file and not previous file

---

pkg/engine/utils/errors.go
pkg/engine/utils/errors_test.go

This commit creates the utils directory for the engine package
for helper functions.
This commit also creates the WrapErr helper function to make
wrapping errors more comfortable. There are also very simple unit
tests to make sure the WrapErr function works properly.

Create utils directory and WrapErr function

---

pkg/engine/ansible.go
pkg/engine/harpoon.go
pkg/engine/kube.go
pkg/engine/kube_test.go
pkg/engine/systemd.go
pkg/engine/utils/errors.go
pkg/engine/utils/errors_test.go
pkg/engine/utils/util.go

@cooktheryan @josephsawaya check this out :1st_place_medal: 
I have picked Joseph's commits from Friday and:
* reset target/method if any error is encountered - with any error _and_ with initial Run, target.method.InitialRun is set to true
* if error is b4 successfully fetching a commit for the target, harpoon will reset/retry the clone each run until it succeeds
* if error is after the initial fetch of a commit, harpoon will reset but will not re-clone on subsequent runs
* with each processMethod run, the resetTarget is called first, (with a nil error) to either set the InitialRun to true/return if errors are detected _or_ to obtain latest commit from remote and continue processing
* with any errors that occur during processing, the `resetTarget` function is called to determine what next …

Better error handling

---

examples/raw/color2.yaml

This commit fixes a typo where the yaml in color2.yaml
specifies a container with the name "colors1" instead of
"colors2"

Fix typo in color2.yaml

---

examples/raw/color2.yaml

This commit fixes a typo in the image url string
in examples/raw/colors2.yaml

Fix typo in image string in colors2 yaml

---

examples/raw/color2.yaml
pkg/engine/harpoon.go
pkg/engine/raw.go

This commit adds support for using yaml files as a
spec for the raw method.
Depends on #131  
Fixes: #77 

Add yaml support for raw method

---

pkg/engine/kube.go
pkg/engine/kube_test.go

This commit replaces the old process for stopping
and removing existing pods, with a call to the
podman API, which is what play.KubeDown() does,
without the need for providing a path to a file
that contains the pod spec for the pod we want to
delete.

Use kube down podman endpoint 

---

pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/kube.go
pkg/engine/raw.go
pkg/engine/systemd.go

This commit separates the path and dest members
of the fileMountOptions struct in order to isolate
those variables for running the engine method
concurrently.

Separate path and dest from file mount options

---

pkg/engine/ansible.go
pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/kube.go
pkg/engine/raw.go
pkg/engine/systemd.go

This commit separates the path member from the fileMountOptions
struct so it can be used concurrently.
This commit also changes the engineMethod to be run concurrently
for different files specified in the method.

Separate path from mo and run engine method concurrently

---

.github/workflows/docker-image.yml
pkg/engine/harpoon.go
pkg/engine/helpers.go
pkg/engine/start.go
systemd/harpoon-root.service
systemd/harpoon-user.service

* starting with empty config file had a bug, this PR fixes it and adds a workflow to test
* also updates the example unit files to mount the config directory with `/opt/mount` since this allows harpoon to start without a config file and only with the $HARPOON_CONFIG_URL
@cooktheryan @josephsawaya

Fix config start

---

.github/workflows/docker-image.yml
examples/systemd-restart.yaml
method_containers/systemd/systemd-script
pkg/engine/harpoon.go
pkg/engine/systemd.go
pkg/engine/types.go

@cooktheryan 
Adding systemd restart services
Expected workflow is to enable the service, then periodically restart the service to pick up any podman `autoupdate=registry` configured unit files. Adds the `SystemdTarget.Restart` boolean

add systemd restart

---

.gitignore
go.mod
go.sum
pkg/engine/kube_test.go

This commit simplifies the kube method tests
by reducing them to only test the kubePodman
function.
This commit also adds the dotenv library to be
used to specify what repository and branch to
use when calling the kubePodman method in the
tests.

Rework kube method tests

---

pkg/engine/raw.go

Flips the ordering a bit to lower the potential downtime of an action

Set the ordering of raw to pull the image before stopping the old

---

examples/config-reload-with-skew.yaml
examples/config-url-with-skew.yaml
examples/full-suite-with-skew.yaml

This commit adds the example configs to use
the skew feature where on users can specify
the length of the window of time they want
harpoon to distribute runs of each method over
in milliseconds.

Add skew example configs

---

.github/workflows/docker-image.yml
README.md
docs/running.rst
systemd/fetchit-root.service
systemd/fetchit-user.service

@cooktheryan @josephsawaya 
This PR
* removes the `disable SELinux, setenforce 0` instructions
* adds `security-opt label=disable` to workflow podman run cmds and the fetchit unit files
* renames harpoon-*.service to fetchit.*service
thanks to @rhatdan for keeping us honest

update unit files and run cmds with --security-opt

---

examples/ansible.yaml
examples/ci-config.yaml
examples/ci-filetransfer-config.yaml
examples/config-reload-with-skew.yaml
examples/config-reload.yaml
examples/config-url-with-skew.yaml
examples/config-url.yaml
examples/default-volume.yaml
examples/filetransfer-config.yaml
examples/full-suite-with-skew.yaml
examples/full-suite.yaml
examples/kube-play-config.yaml
examples/raw-config.yaml
examples/readme-config.yaml
pkg/engine/apply.go
pkg/engine/fetchit.go
pkg/engine/helpers.go

This commit reworks the way fetchit gets changes
and applies them.
The point of this commit is to simplify the fetchit
process in order to make it more clear and extensible.
This commit reduces the previous process for applying
the initial state and following changes to just getting
the current state, getting the latest state, then applying
a method to the difference of those two states. In the case
of an initial apply, the current state is empty. Otherwise
the current state is marked by a git tag on the commit
corresponding to the current state.
This commit also fixes a bug where the scheduler was only
scheduling the first method in the queue to run immediately
rather than all of them.
This commit also removes all calls to the update method
of the fetchit config, since fetchit is using …

Rework git and application processes

---

Dockerfile

We should be able to use the minimal image rather than needing the full image. From testing this reduces the size by 100mb

reduce the size of the container

---

pkg/engine/start.go

With logger, add the AddCaller() option to print filename/linenumber with logging, like so:
```
2022-09-19T15:07:00.102Z	INFO	engine/common.go:99	No changes applied to git target fetchit this run, filetransfer..
```

add caller to logger

---

Dockerfile

It's not infrequent that developers need to build over and over again while working on the code.  Make this a bit faster by caching the result of installing dependencies.  This way, repeatedly building won't perform the same package install over and over again.
Signed-off-by: Chris Evich <cevich@redhat.com>

Speed up repeated builds

---

pkg/engine/start.go

Small convenience update.  Simply set `-e FETCHIT_DEBUG=1` (or any value), and it will start logging debug-level messages.  Given the lack of unit-tests (I hear they're a PITA in golang) being able to switch this on/off will greatly assist developers debugging their own shenanigans.

Add env. var. to enable debug logging

---

.github/workflows/docker-image.yml
pkg/engine/raw.go

This PR aims to help podman track which raw pods are owned by fetchit by applying a `owned-by=fetchit` to the raw pod spec when they are created.
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>

apply owned-by=fetchit label to raw pods

---

README.md
go.mod
go.sum
pkg/engine/systemd.go

As mentioned on #328 I could not figure out how to make the systemd method work as I expected in production. After digging through the code I believe I have figured out how to fix it.
Please share thoughts and concerns on this change. I'm not a Go expert so anything is welcome.
A few notes on this change:
* I couldn't build without running "go mod tidy -go=1.16 && go mod tidy -go=1.17" which changed the go.mod & go.sum.
* Also I had to run "go mod vendor" and added that to the instructions in README.md
* ~~I did not try to tackle a service rename yet, I'm not even sure if it will be processed as a rename.~~
* I have not tried to figure out why the systemd-restart-validate test in .github/workflows/docker-image.yml did not catch this issue

fix systemd restart logic
