containers/fetchit

engine/go.mod
engine/go.sum
engine/main.go
engine/raw.go
examples/config.json
examples/raw/example.json

* List files and only apply diffs
* Only apply files defined in subdirectory

Listing file and apply diff

---

Dockerfile

set workdir where we will mount the config.json

---

.github/workflows/docker-image.yml
examples/raw/example.json

Raw ci job

---

.github/workflows/docker-image.yml

amd64 image fix

---

.github/workflows/docker-image.yml
Dockerfile

Get the image from quay, create a manifest, and push the images

new image location and action patch

---

README.md

podman volumes

---

docs/engine.rst
engine/main.go
examples/config.json

removal of required directory name

---

README.md

directory fix

---

engine/main.go

clean up way we pass method

---

.github/workflows/docker-image.yml

Define specific ordering for push auth

Reverse ordering

---

pkg/engine/raw.go

set the restart policy to be always

---

.gitignore
cmd/harpoon/main.go
go.sum
pkg/engine/raw.go
pkg/engine/systemd.go
pkg/engine/util.go

cut out some repeated code and added error handling

refactor and error handling

---

cmd/harpoon/main.go
examples/engine.json
examples/raw/example.json

allow for github PAT for private repo access

---

.github/workflows/docker-image.yml

Publish Binary as part of a release

---

.github/workflows/docker-image.yml

We should verify all tests before potential image creation

modify needs to ensure all testing is correct

---

pkg/engine/api/types.go
pkg/engine/harpoon.go

@cooktheryan @josephsawaya as noted, there were some flaws in the initial refactoring.
* This PR hopefully fixes those flaws
* finishes the renaming of repo/Repo/Repos -> target/Target/Targets
* finishes the flattening of Repos.Targets to Targets (that nested map thing is gone)
* fixes FindDiff, since it was broken

fix the nested target map

---

.github/workflows/docker-image.yml

update the make changes script

fix make changes

---

.github/workflows/docker-image.yml
examples/filetransfer-config-single-file.yaml
examples/filetransfer-config.yaml
examples/filetransfer/anotherfile.txt
examples/filetransfer/hello.txt
examples/full-suite.yaml
pkg/engine/api/types.go
pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/raw.go
pkg/engine/systemd.go

adding filetransfer logic
still TODO - followup:
- add possibility to execute files?

add filetransfer logic & workflows

---

examples/raw-config.yaml
pkg/engine/api/types.go
pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/raw.go
pkg/engine/systemd.go

If the image already exists on the system do not pull the image. Resolve #82 

if image exists dont pull

---

go.mod
pkg/engine/harpoon.go
pkg/engine/kube.go

This commit refactors the kube method code and
adds handling for file removal for the kube method.
File removal still has to be implemented for the
other methods.
Fixes: #62

Refactor method to add removal to kube method

---

pkg/engine/harpoon.go
pkg/engine/raw.go

This adds handling for removing files in a subdirectory when using the raw method.
Depends on #97 
Fixes: #60

Raw removal

---

pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/systemd.go

This commit adds the file removal feature
to the file transfer method.
Fixes: #61 

file transfer method removal capability

---

pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/systemd.go

This commit adds support for removing systemd files.

systemd method removal

---

.github/workflows/docker-image.yml
examples/ci-filetransfer-config.yaml
pkg/engine/ansible.go
pkg/engine/api/types.go
pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/kube.go
pkg/engine/raw.go

* update git logic to Fetch, Checkout
* save each method's last known commit - that might be different for each method listed per repository
* filter git changes per method  in the findDiff function
* cleanup
* add workflow for addition of files to fileTransfer method
(I also tested addition of a color3 pod/file locally)

Update git diff logic

---

pkg/engine/ansible.go
pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/kube.go
pkg/engine/raw.go
pkg/engine/systemd.go

* only check/pull harpoon image once
* store podman connection/client rather than create multiple
* simplify/standardize parameters to <target>Podman(...) functions - this opens future possiblility of creating a library for & vendoring this code to add arbitrary methods

add FileMountOptions and shared podman connection/client

---

.github/workflows/docker-image.yml
examples/full-suite.yaml

We should fail if color is not correct and containers do not clean themselves after a run 

stricter checks for actions

---

.github/workflows/docker-image.yml
Makefile
docs/methods.rst
examples/full-suite.yaml
examples/systemd-enable.yaml
examples/systemd-non-root-enable.yaml
method_containers/systemd/Dockerfile-systemctl
method_containers/systemd/systemd-script
pkg/engine/api/types.go
pkg/engine/filetransfer.go
pkg/engine/harpoon.go
pkg/engine/systemd.go

This PR 
* adds a simple image, to contain a script that calls systemctl commands on the host
* adds the function to systemd method to enable services, root user
* adds message for non-root users to run `systemctl --user enable service --now` on host to enable service as non-root
* the non-root systemd startup is blocked at this time, need more work with the permissions/mounts/etc
TODO on follow-up:
* add systemd flow to stop & restart (update) services
* add logic for non-root enable

Enable systemd allow nonroot

---

pkg/engine/harpoon.go

This commit changes the getChangesAndRunEngine function in
harpoon.go to run the engine method using goroutines.
This commit also cleans up some unnecessary logging in the
applyInitial function.

make getChangesAndRunEngine concurrent

---

examples/config-reload.yaml
examples/config-url.yaml

update example configs to use main branch

---

pkg/engine/harpoon.go
pkg/engine/helpers.go

* cleanup and a fixes for config reloading
* remove the defaultHostConfig and the filetransfer when processing the config  - I was wrong about that - we don't need this, since the config file will be on the host wherever the mount point of :/opt/mount passed to the podman command is. I dunno what I was thinking, I think I was tired.

config reload fixes

---

pkg/engine/types.go

comments are misleading (aka wrong) in types.go :)

fix comments in types

---

examples/kube/1-example.yaml
examples/kube/2-example.yaml

This commit changes the kube example files to include an
example of creating and using a PVC.

Rewrite kube example files

---

.github/workflows/docker-image.yml
examples/clean-config.yaml
examples/full-suite.yaml
pkg/engine/clean.go
pkg/engine/harpoon.go
pkg/engine/kube_test.go
pkg/engine/types.go

This commit adds the clean method which gives users
the ability to schedule podman system prune runs.
Fixes: #112

Add clean method

---

systemd/harpoon-root.service
systemd/harpoon-user.service

@cooktheryan 
this seems to work

remove env-host from unit files

---

docs/methods.rst

@cooktheryan I missed this one!

quick docs fix

---

.github/workflows/docker-image.yml
examples/systemd-enable-user.yaml
pkg/engine/systemd.go
systemd/harpoon-user.service

systemctl --user enable service and workflow

---

.github/workflows/docker-image.yml
examples/raw-config.yaml
examples/raw/cap.json
examples/raw/cap.yaml
pkg/engine/container.go
pkg/engine/raw.go

Allow for linux capabilities to be added and removed for a container with the raw method
Closes #178

Allow the addition and removal of linux capabilities

---

.github/workflows/docker-image.yml
examples/raw-config.yaml

need to parse out the cap containers and need to point to our repository

---

README.md
docs/methods.rst

Add initial information about ConfigTarget and $FETCHIT_CONFIG_URL env variable

add configTarget info to docs

---

.github/workflows/docker-image.yml
README.md
examples/config-reload-with-skew.yaml
examples/config-reload.yaml
examples/full-suite-with-skew.yaml
examples/full-suite.yaml
examples/raw-config.yaml

To increase the speed of testing we should pull the image once and load it through the various test cases

Pre-pull and save image to allow for testing to be faster

---

pkg/engine/fetchit.go
pkg/engine/types.go

removing unused field lastCommit

lastCommit is no longer needed, removing it

---

pkg/engine/fetchit.go
pkg/engine/types.go

revert fetchitconfig to using plain arrays instead of pointers to arrays

---

.github/workflows/docker-image.yml
examples/imageLoad-config.yaml
examples/imageLoad/byo-image.yaml
pkg/engine/fetchit.go
pkg/engine/image.go
pkg/engine/types.go

fix of the target name
just write the image to memory
CI testing

committing initial image func

---

.github/workflows/docker-image.yml
examples/ansible.yaml
examples/ci-config.yaml
examples/ci-filetransfer-config.yaml
examples/config-reload.yaml
examples/config-url.yaml
examples/filetransfer-config-single-file.yaml
examples/filetransfer-config.yaml
examples/full-suite-with-skew.yaml
examples/full-suite.yaml
examples/glob-config.yaml
examples/kube-play-config.yaml
examples/raw-config.yaml
examples/readme-config.yaml
examples/systemd-autoupdate.yaml
examples/systemd-config-single-file.yaml
examples/systemd-config.yaml
examples/systemd-enable-user.yaml
examples/systemd-enable.yaml
examples/systemd-restart.yaml
go.mod
go.sum
pkg/engine/ansible.go
pkg/engine/apply.go
pkg/engine/common.go
pkg/engine/filetransfer.go
pkg/engine/kube.go
pkg/engine/raw.go
pkg/engine/systemd.go

This PR changes the targetPath configuration option to only accept directories.
This PR also adds the glob option to each method's configuration to be used to filter files in the directory selected using the targetPath configuration option.

Change Target Path to only accept directories

---

Makefile

Signed-off-by: Sally O'Malley <somalley@redhat.com>
@cooktheryan 
@josephsawaya

mistakenly had openshift make targets included, only want golang targets

---

docs/methods.rst

update docs, git targets don't have names

---

pkg/engine/fetchit.go

incorrect method defined

---

pkg/engine/fetchit.go

removes outdated comment and adds a few spaces where there should be

comment fix

---

go.mod
pkg/engine/apply.go

I'm not sure why, but this needs to happen

more klog to zap

---

README.md

readme fix example yaml

---

.github/workflows/docker-image.yml
examples/pat-testing-config.yaml
pkg/engine/ansible.go
pkg/engine/apply.go
pkg/engine/clean.go
pkg/engine/config.go
pkg/engine/fetchit.go
pkg/engine/filetransfer.go
pkg/engine/image.go
pkg/engine/kube.go
pkg/engine/raw.go
pkg/engine/systemd.go
pkg/engine/types.go

inital commit of pat fix

---

docs/methods.rst
docs/running.rst
examples/config-url.yaml
pkg/engine/apply.go
pkg/engine/config.go
pkg/engine/fetchit.go
pkg/engine/types.go

commit of basic auth

---

docs/methods.rst

fix of doc format

---

docs/methods.rst

Signed-off-by: Sally O'Malley <somalley@redhat.com>

fix yaml format

---

Dockerfile
pkg/engine/container.go

flip to using rsync vs cp

---

docs/index.rst
docs/methods.rst

needed a blank line

---

.github/workflows/docker-image.yml
pkg/engine/systemd.go

need to build and push rpi images

---

.github/workflows/docker-image.yml
Dockerfile

Reverts containers/fetchit#255

Revert "Build rpi"

---

.github/workflows/docker-image.yml
pkg/engine/systemd.go

Reverts containers/fetchit#253

Revert "need to build and push rpi images"

---

.github/workflows/docker-image.yml
docs/index.rst
examples/ssh-config.yaml
pkg/engine/apply.go
pkg/engine/config.go
pkg/engine/fetchit.go
pkg/engine/filetransfer.go
pkg/engine/gitauth.go
pkg/engine/types.go

This pull request allows the user to access their source github repo via ssh. Https functionality is still intact, but ssh will be used if specified in the config file. 
Resolves issue #244 
Signed-off-by: djach7 <djachimo@redhat.com>

Add ability to access git over ssh

---

README.md

add how to develop

---

.github/workflows/docker-image.yml
Dockerfile
docs/methods.rst
scripts/entry.sh

This pull request adds the ability to configure FetchIt by specifying the `FETCHIT_CONFIG` environment variable.
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>

Add support for config via environment variable

---

.github/workflows/docker-image.yml
examples/pat-testing-kube.yaml

pat check for kube

---

docs/methods.rst
examples/pat-testing-config.yaml
examples/pat-testing-kube.yaml

emegency doc fix

---

.github/workflows/docker-image.yml
docs/methods.rst
examples/podman-secret-raw-config.yaml
examples/podman-secret-raw.yaml
pkg/engine/apply.go
pkg/engine/config.go
pkg/engine/fetchit.go
pkg/engine/gitauth.go
pkg/engine/types.go

podman secret usage
